<?php
/**
 * module-testcase:/unit/i18n/javascript.php
 *
 * @creation  2019-05-04
 * @version   1.0
 * @package   module-testcase
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** namespace
 *
 * @creation  2019-04-08
 */
namespace OP;

?>
<p data-i18n="true" data-locale="en:US">Translate is successful!!</p>
<p data-i18n="true" data-locale="">Translation fails here.</p>
<p data-i18n="true" data-locale="en:GB">Do you like <b>Apple</b>?</p>
<p data-i18n="true" data-locale="en:US">Do you like <b>Apple</b>?</p>
<p data-i18n="true" data-locale="en:US">Do you like <b data-i18n="false">"Apple"</b> or "<i data-i18n="false">Orange</i>" or <a href="./banana">Banana</a>?</p>
