<?php
/**
 * module-testcase:/unit/i18n/menu.phtml
 *
 * @creation  2019-04-08
 * @version   1.0
 * @package   module-testcase
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** namespace
 *
 * @creation  2019-04-08
 */
namespace OP;

?>
<section>
	|
	<a href="selftest" >Selftest</a>  |
	<a href="languages">Languages</a> |
	<a href="translate">Translate</a> |
	<a href="javascript">JavaScript</a> |
</section>
